plugins {
    id 'com.android.application'
}

def configuredWebAppUrl = project.findProperty('webAppUrl') ?: 'http://10.0.2.2:3000'

android {
    namespace 'br.mg.bambui.filasaude'
    compileSdk 35

    defaultConfig {
        applicationId 'br.mg.bambui.filasaude'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
        buildConfigField 'String', 'WEB_APP_URL', "\"${configuredWebAppUrl}\""
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
